name: Deploy CloudFormation

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: List Files
        run: ls -R
        working-directory: ${{ github.workspace }}

      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --stack-name TestVPC \
            --template-file TestStack.yaml \
            --parameter-overrides CustomKeyName=vockey \
            --capabilities CAPABILITY_NAMED_IAM


