name: Deploy CloudFormation Template

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: List files (confirm template exists)
        run: ls -la

      - name: Validate CloudFormation template
        run: aws cloudformation validate-template --template-body file://main-code.yaml

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file main-code.yaml \
            --stack-name my-main-stack \
            --parameter-overrides KeyName=vockey \
            --no-fail-on-empty-changeset

      - name: If deploy fails - show stack events
        if: failure()
        run: |
          aws cloudformation describe-stack-events \
            --stack-name my-main-stack \
            --query "StackEvents[0:20].[LogicalResourceId,ResourceType,ResourceStatus,ResourceStatusReason]" \
            --output table
