# name: Deploy CloudFormation
# on:
#   workflow_dispatch:
# jobs:
#     deploy:
#     runs-on: ubuntu-latest
#  steps:
#        - name: Configure Repo
#         uses: actions/checkout@v4
#        - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
#           aws-region: us-east-1
#        - name: List Files
#         run: ls -R
#         working-directory: ${{ github.workspace }}
#        - name: Deploy CloudFormation Stack
#          run: |
#           aws cloudformation deploy \
#             --stack-name TestVPC \
#             --template-file TestStack.yaml \
#             --capabilities CAPABILITY_NAMED_IAM


name: Deploy CloudFormation Template

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file main-code.yaml \
            --stack-name my-main-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset